services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - orders
    restart: always

  backend:
    build:
      context: ./backend
    environment:
      - DB_HOST=postgres
      - DB_NAME=marketplace
      - DB_USER=root
      - DB_PASS=rootpassword
    depends_on:
      - postgres
    restart: always

  orders:
    build:
      context: ./orders
    environment:
      - DB_HOST=postgres
      - DB_NAME=marketplace
      - DB_USER=root
      - DB_PASS=rootpassword
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: marketplace
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  postgres_data: