apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: uubj
spec:
  replicas: 1
  selector: { matchLabels: { app: frontend } }
  template:
    metadata: { labels: { app: frontend } }
    spec:
      containers:
      - name: frontend
        image: uubj-frontend:dev
        ports: [{ containerPort: 80 }]
        readinessProbe:
          httpGet: { path: "/", port: 80 }
          initialDelaySeconds: 2
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits:   { cpu: "200m", memory: "128Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: uubj
spec:
  selector: { app: frontend }
  ports: [{ port: 80, targetPort: 80 }]
  type: ClusterIP
